apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: xrootd-tpc
  name: tpc-greatplains
  namespace: osg
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: xrootd-tpc
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: osg.kans.nrp.internet2.edu
      initContainers:
      - name: chowndata
        image: busybox
        volumeMounts:
        - name: datavol
          mountPath: /data/stash
      containers:
      - name: stashcache
        resources:
           limits:
              memory: 14Gi
           requests:
              memory: 10Gi
        image: efajardo/xrootd-tpc
        #command: ["sh", "-c", "sleep infinity"]
        env:
        - name: XRDHTTPPORT
          value: "9002"
        - name: SITENAME
          value: XrootdTPCPRP
        imagePullPolicy: Always
        volumeMounts:
        - name: hostcert
          mountPath: /etc/grid-security/hostcert.pem
        - name: hostkey
          mountPath: /etc/grid-security/hostkey.pem
        - name: config
          mountPath: /etc/xrootd
        - name: datavol
          mountPath: /data/stash
        - name: secret-key
          mountPath: "/etc/xrootd/security"
          readOnly: true
      volumes:
      - name : secret-key
        secret: 
          secretName: secretkey
      - name : hostcert
        hostPath:
           path: /etc/grid-security/hostcert.pem
           type: File
      - name : hostkey
        hostPath:
           path: /etc/grid-security/hostkey.pem
           type: File
      - name: config
        configMap:
          name: xrootd-tpc
      - name: datavol
        hostPath:
          path: /tank
          type: Directory
